In [ ]:
import datasets
import pandas as pd

/Users/pepijnvanderklei/miniforge3/envs/fact/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

╭───────────────────────────────────────────── 🚀 New SDK Available ──────────────────────────────────────────────╮
│ Together Python SDK 2.0 is now available!                                                                       │
│                                                                                                                 │
│ Install the beta:                                                                                               │
│ pip install --pre together  or  uv add together --prerelease allow                                              │
│                                                                                                                 │
│ New SDK: ]8;id=949658;https://github.com/togethercomputer/together-py\https://github.com/togethercomputer/together-py]8;;\                                                        │
│ Migration guide: ]8;id=813986;https://docs.together.ai/docs/pythonv2-migration-guide\https://docs.together.ai/docs/pythonv2-migration-guide]8;;\                                         │
│                                                                                                                 │
│ This package will be maintained until January 2026.                                                             │
│ Set TOGETHER_NO_BANNER=1 to hide this message.                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

# First we load the datasets from Hugging Face

In [2]:
candidateprofiles = datasets.load_dataset("lang-uk/recruitment-dataset-candidate-profiles-english")
jobdescriptions = datasets.load_dataset("lang-uk/recruitment-dataset-job-descriptions-english")

# Make Pandas DataFrames from the datasets

In [4]:
jobdescriptions_df = jobdescriptions["train"].to_pandas()
candidateprofiles_df = candidateprofiles["train"].to_pandas()

In [5]:
candidateprofiles_df.head()

,Position,Moreinfo,Looking For,Highlights,Primary Keyword,English Level,Experience Years,CV,CV_lang,id,__index_level_0__
0,"13 years of exp || Solidity, C#, JavaScript ||...",Who am I:\r\n- 13 years of commercial experien...,I am interested in:\r\n- part-time engagement;...,Landed a role of Director of Blockchain Develo...,Lead,fluent,11.0,Landed a role of Director of Blockchain Develo...,en,50534b61-6826-52b1-9ac5-bfd2cfa348ec,24230
1,1c Developer,Worked on a mobile application for tracking trips,None,None,Other,intermediate,3.0,\nWorked on a mobile application for tracking ...,en,c2b9ea56-b5c8-50ec-a63b-053a5c8ff467,24231
2,1C developer,1 am an 1C developer. I deployed an 1C to typo...,None,None,Flutter,intermediate,11.0,\n1 am an 1C developer. I deployed an 1C to ty...,en,b3bfe3ed-ec25-56b2-8aaa-8c629120538e,24232
3,1C Developer,Perfect knowledge of 1C:Enterprise Platform.\...,None,None,Other,intermediate,11.0,\nPerfect knowledge of 1C:Enterprise Platform...,en,163fb9a3-3695-5dc3-b1d0-e0038ce4d0a5,24233
4,#1 Customer Support Specialist,"Tech addicted, experienced customer support wi...",In terms of the nature of the Customer Support...,"thousands of resolved problems, also, thousand...",Support,fluent,2.5,"thousands of resolved problems, also, thousand...",en,3f201183-db58-5333-9139-74c16059dc4a,24234

In [9]:
jobdescriptions_df.head()

,Position,Long Description,Company Name,Exp Years,Primary Keyword,English Level,Published,Long Description_lang,id,__index_level_0__
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...,MyCointainer,2y,Sysadmin,intermediate,2020-10-01T00:00:00+03:00,en,c0ca96e7-85df-50df-a64e-d934cd02a170,27461
1,10 .NET Developers (Middle and Senior level),"Greetings! My name is Maria, I am in urgent ne...",TechScout.tech,2y,.NET,intermediate,2022-03-01T00:00:00+02:00,en,64f4b7ea-36e4-5bdd-a8b1-185f32f7dc7f,27462
2,"10X Engineer (co-founder, #4 employee, USD 11-...",**Product**\r\nThe product is a live video cha...,Innoteka,5y,JavaScript,fluent,2021-07-01T00:00:00+03:00,en,b9a1303e-dd0c-5ed1-8f62-be2bc4c7da4f,27463
3,16 - Amazon Brand Manager,"Currently, TCM expanding its activities to Ukr...",FirstFive,2y,Marketing,upper,2022-01-01T00:00:00+02:00,en,99cb3f4a-9b4b-53d9-9a3b-bab2c22da346,27464
4,16 - Amazon Brand Manager,"Hello,\r\nWe, MIMIRB2B, are an outstaff compan...",MimirB2B,1y,Marketing,upper,2021-12-01T00:00:00+02:00,en,bc1419f7-28e2-582b-8d53-22e28b2f0210,27465

# We take all UI/IX and Project Manager CVs

In [6]:

uiux_df = candidateprofiles_df[candidateprofiles_df["Position"].str.contains("UI/UX Designer", na=False)]
pm_df = candidateprofiles_df[candidateprofiles_df["Position"].str.contains("Project Manager", na=False)]

# Take the first 260 from both

In [13]:
uiux_first_260_df = uiux_df.head(260).copy()
pm_first_260_df = pm_df.head(260).copy()

# And concatenate them

In [ ]:
uiux_first_260_df.loc[:, "Position Group"] = "UI/UX Designer"
pm_first_260_df.loc[:, "Position Group"] = "Project Manager"

uiux_pm_520_df = pd.concat([uiux_first_260_df, pm_first_260_df])

# Save to a CSV file

In [ ]:
uiux_pm_520_df.to_csv("uiux_pm_520_original_cvs.csv")